### ISSUE TITLE
Creating a tenant from UI

### ISSUE THREAD

**Issue by kartiksura** [kiegroup/optaweb-employee-rostering#172]
Is creating a new tenant from the UI supported? I created one using the API:

I am able to create:
1. Skills
2. Employees
3. Spots

But not able to access any new Roster or access the Rotation page:
java.lang.IllegalStateException: Error calling REST method with status (500: Internal Server Error) and text (No entity found for queryorg.hibernate.jpa.internal.QueryImpl.getSingleResult(QueryImpl.java:532)
org.optaplanner.openshift.employeerostering.server.roster.RosterRestServiceImpl.getRosterState(RosterRestServiceImpl.java:377)
org.optaplanner.openshift.employeerostering.server.roster.RosterRestServiceImpl$Proxy$_$$_WeldSubclass.getRosterState(Unknown Source)
org.optaplanner.openshift.employeerostering.server.roster.RosterRestServiceImpl.getCurrentShiftRosterView(RosterRestServiceImpl.java:74)
org.optaplanner.openshift.employeerostering.server.roster.RosterRestServiceImpl$Proxy$_$$_WeldSubclass.getCurrentShiftRosterView$$super(Unknown Source)
s

**Comment by Christopher-Chianelli** [comment]
Support for adding a Tenant from the UI was added in commit [a55e680ea9aa62a53762529adee9790758e5f09f](https://github.com/kiegroup/optaweb-employee-rostering/commit/a55e680ea9aa62a53762529adee9790758e5f09f). You can find the "Add Tenant" button in the Admin page. Additionally, the UI will still work if you create the tenant from the API (and you have the ability to delete tenants now). Closing.
