### ISSUE TITLE
Openshift local build fails due to maven.min.version

### ISSUE THREAD

**Issue by MusaTalluzi** [kiegroup/optaweb-employee-rostering#254]
Deploying the app on Openshift local cluster fails with a message:
```
[WARNING] Rule 0: org.apache.maven.plugins.enforcer.RequireMavenVersion failed with message:
To build this project Maven 3.5.2 (or greater) is required. Please install it.
```

Environment:
```
oc v3.9.0
kubernetes v1.9.1+cbc5b49
```

Steps to reproduce:
```
oc cluster up
oc new-project optaweb-employee-rostering
oc new-app --image-stream="openshift/wildfly:10.1" https://github.com/kiegroup/optaweb-employee-rostering.git#master
```

Reason:
oc v3.9.0 s2i version [supports Maven 3.3.9-2.8](https://docs.okd.io/3.9/using_images/s2i_images/java.html#s2i-images-java-versions) while `maven.min.version` was updated to 3.5.2 in [7.23.x](https://github.com/kiegroup/droolsjbpm-build-bootstrap/blob/b98e76626c9fe0d2c84cf0418bc0d30146514a24/pom.xml#L200).

**Comment by TomHarrop** [comment]
I have this issue too with oc 3.11.0

```bash
$ oc version
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO
```

```bash
[WARNING] Rule 0: org.apache.maven.plugins.enforcer.RequireMavenVersion failed with message:
To build this project Maven 3.5.2 (or greater) is required. Please install it.
```

**Comment by Soulblazer91** [comment]
> Deploying the app on Openshift local cluster fails with a message:
> 
> ```
> [WARNING] Rule 0: org.apache.maven.plugins.enforcer.RequireMavenVersion failed with message:
> To build this project Maven 3.5.2 (or greater) is required. Please install it.
> ```
> 
> Environment:
> 
> ```
> oc v3.9.0
> kubernetes v1.9.1+cbc5b49
> ```
> 
> Steps to reproduce:
> 
> ```
> oc cluster up
> oc new-project optaweb-employee-rostering
> oc new-app --image-stream="openshift/wildfly:10.1" https://github.com/kiegroup/optaweb-employee-rostering.git#master
> ```
> 
> Reason:
> oc v3.9.0 s2i version [supports Maven 3.3.9-2.8](https://docs.okd.io/3.9/using_images/s2i_images/java.html#s2i-images-java-versions) while `maven.min.version` was updated to 3.5.2 in [7.23.x](https://github.com/kiegroup/droolsjbpm-build-bootstrap/blob/b98e76626c9fe0d2c84cf0418bc0d30146514a24/pom.xml#L200).

Were you able to find a resolution to this? I have updated my maven to 3.6.2 yet it still fails me. Is there a embedded maven package that openshift uses we need to update somehow?
