### ISSUE TITLE
Solving ETA shouldn't be hard-coded on frontend

### ISSUE THREAD

**Issue by yurloc** [kiegroup/optaweb-employee-rostering#280]
Where does this magic constant come from? Is it related to termination in solver config on the backend? What happens if you change solver config and forget to update the solving length value?

_Originally posted by @yurloc in https://github.com/kiegroup/optaweb-employee-rostering/pull/276#discussion_r324583462_

Currently the frontend assumes solver is solving for 30s. After that interval, frontend state is updated (terminate button hides, solve button shows up) and shift roster is updated.

1. If solver config changes, this hard-coded frontend constant needs to be updated too. This can be solved by a response to `/solve` that would contain ETA. Frontend will know when to chnage state to `!isSolving'.

2. If solver terminations changes from time-based to score-based or number of steps, ETA will become unpredictable and frontend will need to poll for solver state.

**Comment by Christopher-Chianelli** [comment]
The frontend been updated to poll for solver state. closing.
