### ISSUE TITLE
Not possible to search by substring in Shift, Availability, Rotation

### ISSUE THREAD

**Issue by yurloc** [kiegroup/optaweb-employee-rostering#306]
## Expected behavior
- Shift, Rotation page: search for 'logy' => Cardiology, Neurology, ...
- Availability: search for 'fox' => Amy Fox, Beth Fox, ...

**Comment by Christopher-Chianelli** [comment]
It is half possible, the Select is searchable by prefix (which is the default for Patternfly; need to use onFilter to change the filter to the substring one).
