### ISSUE TITLE
Help needed in testing 'backend' without DEMO_DATA

### ISSUE THREAD

**Issue by JimmyKer** [kiegroup/optaweb-employee-rostering#389]
Hi,

I'm using Windows10 with Java JDK 13.0.2, NodeJS 12.16, Maven 3.6.3.
I'm able to start the backend and Frontend:
```
mvn spring-boot:run -Doptaweb.generator.initial.data=EMPTY

cd optaweb-employee-rostering-frontend
npm start

```
I'm unable to reproduce the required steps to implement the system property [optaweb.generator.initial.data](https://github.com/kiegroup/optaweb-employee-rostering/blob/master/optaweb-employee-rostering-docs/src/main/asciidoc/Introduction/SystemProperties/SystemProperties-section.adoc)

Can someone provide a step-by-step how to start the backend with the property 'EMPTY'?

**My goal is to make tenant changes persistant over a reboot from the backend.**

Kind regards

**Comment by Christopher-Chianelli** [comment]
To **start with an empty dataset**, the command to run is `java -Doptaweb.generator.initial.data=EMPTY -jar optaweb-employee-rostering-standalone/target/optaweb-employee-rostering-standalone-*-exec.jar`.

To **make tenant changes persist across reboots**, the command to run is `java -Doptaweb.generator.initial.data=EMPTY -Dspring.profiles.active=production -jar optaweb-employee-rostering-standalone/target/optaweb-employee-rostering-standalone-*-exec.jar`. This expects a postgres database. You need to set the following environment variables:

- **DATABASE_NAME**: The name of the postgres database.
- **DATABASE_USER**: The name of the database user.
- **DATABASE_PASSWORD**: The password for DATABASE_USER in the database.
- (optional) **DATABASE_HOST**: the address where the database is located (defaults to postgresql).

Alternatively, you could use `runOnOpenShift.sh` script, which will create a new application in your OpenShift account with three components: the Postgres database, the backend server, and the frontend server. It will automatically run in production mode (so changes will be persisted). You would need to delete the demo data though.

**Comment by JiangWeian** [comment]
@Christopher-Chianelli , since empty data, I also encountered a problem. After I added skills and contracts, they could not be displayed. But Postgres database. But records are inserted into the database. How to solve this problem?

**Comment by Christopher-Chianelli** [comment]
@JiangWeian Did you create a tenant? If you start with an empty dataset, you first need to create a Tenant. Click the gear icon and add a Tenant from there (You might need to refresh the page afterwards).

**Comment by JiangWeian** [comment]
@Christopher-Chianelli , OK, I've learned to create data from Tenant. Thank you.

**Comment by otherwish** [comment]
> To **start with an empty dataset**, the command to run is `java -Doptaweb.generator.initial.data=EMPTY -jar optaweb-employee-rostering-standalone/target/optaweb-employee-rostering-standalone-*-exec.jar`.
> 
> To **make tenant changes persist across reboots**, the command to run is `java -Doptaweb.generator.initial.data=EMPTY -Dspring.profiles.active=production -jar optaweb-employee-rostering-standalone/target/optaweb-employee-rostering-standalone-*-exec.jar`. This expects a postgres database. You need to set the following environment variables:
> 
> * **DATABASE_NAME**: The name of the postgres database.
> * **DATABASE_USER**: The name of the database user.
> * **DATABASE_PASSWORD**: The password for DATABASE_USER in the database.
> * (optional) **DATABASE_HOST**: the address where the database is located (defaults to postgresql).
> 
> Alternatively, you could use `runOnOpenShift.sh` script, which will create a new application in your OpenShift account with three components: the Postgres database, the backend server, and the frontend server. It will automatically run in production mode (so changes will be persisted). You would need to delete the demo data though.

I am trying to get this running via docker and having trouble with the external database connection. Are there default variables for the Postgres database? I would assume adding -v variables to the run command would be enough, but struggling to make the connection work.

**Comment by cardpac** [comment]
> To **start with an empty dataset**, the command to run is `java -Doptaweb.generator.initial.data=EMPTY -jar optaweb-employee-rostering-standalone/target/optaweb-employee-rostering-standalone-*-exec.jar`.
> 
> To **make tenant changes persist across reboots**, the command to run is `java -Doptaweb.generator.initial.data=EMPTY -Dspring.profiles.active=production -jar optaweb-employee-rostering-standalone/target/optaweb-employee-rostering-standalone-*-exec.jar`. This expects a postgres database. You need to set the following environment variables:
> 
> * **DATABASE_NAME**: The name of the postgres database.
> * **DATABASE_USER**: The name of the database user.
> * **DATABASE_PASSWORD**: The password for DATABASE_USER in the database.
> * (optional) **DATABASE_HOST**: the address where the database is located (defaults to postgresql).
> 
> Alternatively, you could use `runOnOpenShift.sh` script, which will create a new application in your OpenShift account with three components: the Postgres database, the backend server, and the frontend server. It will automatically run in production mode (so changes will be persisted). You would need to delete the demo data though.

Hi, are the environment variables configured in `optaweb-employee-rostering-standalone\src\main\resources\application.properties`? I'm trying to connect and create a `postgreSQL`  employee rostering database without data.  


optaweb-employee-rostering-standalone\src\main\resources\application.properties:
```
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/employeerostering
quarkus.datasource.username=postgres
quarkus.datasource.password=password
quarkus.hibernate-orm.database.generation=drop-and-create
```

error:
```
One or more configuration errors have prevented the application from starting. The errors are:
  - SRCFG00011: Could not expand value DATABASE_NAME in property quarkus.datasource.jdbc.url
  - SRCFG00011: Could not expand value DATABASE_USER in property quarkus.datasource.username
  - SRCFG00011: Could not expand value DATABASE_PASSWORD in property quarkus.datasource.password
```

**Comment by Christopher-Chianelli** [comment]
@cardpac Quarkus get its environment variables from several sources (https://quarkus.io/guides/config-reference#configuration-sources). Typically System Properties / `.env` file is used for secrets that should not be committed to a repository, while application.properties is used for general application properties that should be committed to the repository. The `optaweb.generator.initial.data=EMPTY` can be put in `application.properties` if desired, or passed as a system property to java `java -Doptaweb.generator.initial.data=EMPTY ...`

The errors you got is because the `DATABASE_NAME`, `DATABASE_USER`, `DATABASE_PASSWORD` environment variables are not defined, which the standalone `application.properties` references: https://github.com/kiegroup/optaweb-employee-rostering/blob/main/optaweb-employee-rostering-standalone/src/main/resources/application.properties . If you define these variables in a `.env` file or as regular environment variables (in bash, `export DATABASE_NAME=name`), it should work.
