### ISSUE TITLE
Unable to pin

### ISSUE THREAD

**Issue by magick93** [kiegroup/optaweb-employee-rostering#408]
Hello

I'm unable to enable a pin for a a shift, either a new or existing shift.

# Steps to reproduce

1. Using version (`git describe`) 0.1.0-1091-g04844f35
1. `mvn clean install -DskipTests -DskipITs`
1. `java -jar optaweb-employee-rostering-standalone/target/optaweb-employee-rostering-standalone-*-exec.jar`
1. Open brower, ether FF or Chrome, on Ubuntu 19, go to, for example http://localhost:8080/55417/shift?spot=Airbag+line+15
1. Click like a maniac on the `Is Pinned` toggle switch.

# Expected result

Expect I can change the pin state. And am hoping this will also be visually represented.

It is the same issue on either an existing, or when creating a new, shift.

**Comment by Christopher-Chianelli** [comment]
Thanks for reporting. It look like a dependency component changed from being controlled to uncontrolled, or vice-versa, since it was working before.

**Comment by Christopher-Chianelli** [comment]
Can confirm it related to the `Switch` dependency; the `onChange` event is not even firing, and I can't find anything related to `pointer-events` that could be messing with it. Firing the event manually from the inspector works.

**Comment by Christopher-Chianelli** [comment]
Found a fix: Add `id` field to `Switch`. It wasn't required before and doesn't log a warning in the console (before you could use `aria-label` in lieu of `id`).

**Comment by Christopher-Chianelli** [comment]
Fix: https://github.com/kiegroup/optaweb-employee-rostering/pull/410 (BTW, this is visually represented in the UI as a Pin Icon on the Shift itself, and the checkbox will be blue with a checkmark when on)
