### ISSUE TITLE
equals and hashCode in AbstractPersistable 

### ISSUE THREAD

**Issue by pixnbit** [kiegroup/optaweb-employee-rostering#472]
I noticed these two methods are overridden with just comparing the ID fields. Is it necessary to have this for the rostering backend functioning? I found it to be weird, and the Optalanner examples stated the same reason:

https://github.com/kiegroup/optaplanner/blob/ed61375f66cb2a8ea888b9acf9759524b081fa14/optaplanner-examples/src/main/java/org/optaplanner/examples/common/domain/AbstractPersistable.java#L41

**Comment by triceo** [comment]
The reason for `AbstractPersistable` to exist is that we do want all domain classes to share some properties - specifically, `@PlanningId`. And in the case of this project, it probably makes sense to have ID-based equality, and therefore to implement `equals` and `hashCode` in `AbstractPersistable` directly.

However, this code has originally been copied from https://github.com/kiegroup/optaplanner, where the purpose for `AbstractPersistable` is a bit blurrier - we can not guarantee that all users would always want to mix identification of an object via `@PlanningId` with equality, for which they may also want to use other fields. After copying the code into this project, that decision has not been re-evaluated. Perhaps it could be, but I personally don't see anything forcing us to do this.

As this is not an issue and more of a request for information, I am closing it. Feel free to reopen if this is causing an actual issue for you somehow.

**Comment by pixnbit** [comment]
Thanks for the detailed explanation @triceo! Btw, I really like your work on the stream-based constraint provider, this allows much easier dynamic configuration in code!

**Comment by triceo** [comment]
Thanks! Stay tuned, there's more where Constraint Streams came from. ;-)
