### ISSUE TITLE
What is the difference, function and connection between rotation and shift? Is the data in the two pages related?

### ISSUE THREAD

**Issue by JiangWeian** [kiegroup/optaweb-employee-rostering#483]

**Comment by Christopher-Chianelli** [comment]
The function of Rotation is to give a consistent schedule that repeats every N weeks to employees (so they can plan their life around it; for instance, Employee Amy might work a week of day, a week of afternoon, and a week of nights, and then it repeats). The Rotation represents what SHOULD happen in a perfect world.

But alas, the world is not perfect. People get sick, additional shifts might be required for another day, etc. So the Shift screen reflects reality. OptaPlanner tries to assign shifts to their designated rotation employee (the rotation employee is taken from the rotation and is chosen whenever you provision or publish shifts), but can assign it to another employee if is impossible to assign the rotation employee to that shift (if they're sick, needed for another shift, etc.)

To see how this works, look at
https://www.optaplanner.org/learn/slides/optaplanner-presentation/index.html#/4/22 (it a presentation, so you need to press the down arrow to see all the parts)

**Comment by JiangWeian** [comment]
@Christopher-Chianelli , If I don't have rotation page data, where does rotation data come from? As you should know, rotating page data is also a kind of scheduling that an ideal situation. It's up to us to arrange rotation employee manually?

**Comment by Christopher-Chianelli** [comment]
You edit the rotation in the Rotation screen. We recently did an overhaul to the Rotation system to make it more convenient. If you are using master, you create Time Buckets, which are shifts that are repeated for a certain timeslot for a certain Spot (as an example: Wheels from 9am-5pm is a Time Bucket). After you create your Time Buckets, you create an Employee Palette for the employees in the rotation for the particular Spot (maybe it Amy, Beth and Charlie). You then select the employee from the Palette and click and drag the mouse over the days in the rotation you want the employee to work in that particular time bucket. When that is all done, you have a completed rotation. If you are using the old version, it would be like creating shifts.
