### ISSUE TITLE
If I want to modify the table name (the class name does not change), how to operate?

### ISSUE THREAD

**Issue by JiangWeian** [kiegroup/optaweb-employee-rostering#485]
I tried to add name to @Entity and @Table and modify some SQL statements displayed. The table passed the generation, but the test data could not be generated:
@Entity(name = "PACSDATA_HOSPITAL")
@Table(name = "PACSDATA_HOSPITAL", uniqueConstraints = @UniqueConstraint(columnNames = { "name" }))
public class Tenant {

**Comment by Christopher-Chianelli** [comment]
You probably also need to modify the table name used in the Repository Queries (for instance, the query in https://github.com/kiegroup/optaweb-employee-rostering/blob/master/optaweb-employee-rostering-backend/src/main/java/org/optaweb/employeerostering/service/tenant/TenantRepository.java)

**Comment by JiangWeian** [comment]
@Christopher-Chianelli , I have modified the SQL statement in @Query:

@Repository
public interface TenantRepository extends JpaRepository<Tenant, Integer> {

    @Query("select t from PACSDATA_HOSPITAL t " +
    // Deliberately order by id instead of name to use generated order
            "order by t.id")
    List<Tenant> findAll();
}
