### ISSUE TITLE
Rotation screen: employee stub disappears when creating a new time bucket

### ISSUE THREAD

**Issue by rsynek** [kiegroup/optaweb-employee-rostering#488]
1. Empty the buckets and Employee Stub on the Rotation screen.
2. Create a new Employee Stub

![creating_time_bucket](https://user-images.githubusercontent.com/1422582/90521080-6c6bab80-e16a-11ea-8274-68d9a76b543f.png)

3. Create a new Time Bucket
4. Employee Stub created in step 2. disappears

![time_bucket_created](https://user-images.githubusercontent.com/1422582/90521359-b81e5500-e16a-11ea-8c73-e1aed928cc0e.png)

**Comment by JiangWeian** [comment]
@rsynek , is this because employee stub is not saved into the database?

**Comment by Christopher-Chianelli** [comment]
The Employee Stubs list is calculated from the employees in the timebuckets. So when you add a new timebucket, that list is recalculated. The main use is for when you change spots, which may have different employees in the employee stub list.
