### ISSUE TITLE
Daily minutes must not exceed contract maximum

### ISSUE THREAD

**Issue by miyamoza** [kiegroup/optaweb-employee-rostering#491]
The `rule "No more than 2 consecutive shifts"` creates the following situations provided we have two types of shifts:

- Shift 1 starts at 08:30 ~ 16:30 finishes the same day
- Shift 2 starts at 16:30 ~ 08:30 finishes the next day

![image](https://user-images.githubusercontent.com/61220501/91242589-d09df900-e782-11ea-9282-b02699a97bb4.png)

The situation on the left (31 Mon ~ 01 Tue) where the employee E1 is assigned first to Shift 1 followed by Shift 2 is desired.
However, the situation on the right (02 Wed ~ 03 Thu) where the employee E2 is assigned first to Shift 2 and then to Shift 1 is not desired. A night shift followed by a day shift is not really desired even in real life.

My first instinct was to limit the number of hours per day from the `Contract` settings and technically it should have worked:

- Shift 1 is 08:30 ~ 16:30 8h * 60min = 480min
- Shift 2 until midnight 16:30 ~ 00:00 7.5h * 60min = 450min

So, if I was to limit the number of minutes to 930min/day then the assignment Shift 1 followed by Shift 2 would be allowed, while Shift 2 followed by Shift 1 would not be allowed (because this order of assignment would take 990min/day)

Unfortunately, this trick didn't work and I realized that the contract **maximum number of minutes / day** are not really calculated based on the end of the day, but based on the end of the shift. 

Any ideas on how to allow Shift 1 followed by Shift 2 but not the other way around?

Thank you.

**Comment by Christopher-Chianelli** [comment]
What is the goal of your constraint? Is it "All consecutive shifts must start on the same day"? If so, this should work:
```
rule "All consecutive shifts must start on the same day"
    when
        $s : Shift(
                employee != null,
                $e : employee,
                $firstStartDateTime : startDateTime,
                $firstEndDateTime : endDateTime)
        $s2: Shift(
                employee == $e,
                $firstEndDateTime == startDateTime,
                this != $s,
                $firstStartDateTime.toLocalDate() != startDateTime.toLocalDate())
    then
        scoreHolder.penalize(kcontext, $s.getLengthInMinutes() + $s2.getLengthInMinutes());
end
```

**Comment by miyamoza** [comment]
Thank you @Christopher-Chianelli 
this may actually work.
Do I need to modify the `EmployeeRosteringConstraintProvider` also? Or simply adding the DRools would work!

**Comment by Christopher-Chianelli** [comment]
If you haven't enabled the ConstraintProvider by uncommenting this line:
https://github.com/kiegroup/optaweb-employee-rostering/blob/a1dd3422962e88d2e330ce0695552814a802a8b3/optaweb-employee-rostering-backend/src/main/resources/solverConfig.xml#L5,
then you only need to modify the Drools file (the default).

If you enabled the ConstraintProvider, you only need to add the Java version of that constraint to the ConstraintProvider, and don't need to modify the Drools.

**Comment by miyamoza** [comment]
@Christopher-Chianelli 
it worked. thank you.
