### ISSUE TITLE
Delete employee button not working; schedule button unresponsive

### ISSUE THREAD

**Issue by dlymarg** [kiegroup/optaweb-employee-rostering#495]
Hi, I tried deleting an employee from the database ( similar to #73 ) to reduce the load on the scheduler when trying to schedule employees, but I kept getting the following errors (both within the UI and within the console):

<img width="1440" alt="Screen Shot 2020-09-11 at 4 45 08 PM" src="https://user-images.githubusercontent.com/41245477/92972051-92c1f580-f44f-11ea-9d4b-5c59aa58d1ac.png">

After clicking 'See Stack Trace' on the top right, this is what I get:

<img width="1440" alt="Screen Shot 2020-09-11 at 4 45 17 PM" src="https://user-images.githubusercontent.com/41245477/92972076-9ce3f400-f44f-11ea-869d-e2b17cc36f8e.png">

These are the messages the console returns after attempting to delete an employee from the database:

```
2020-09-11 16:45:12.449  WARN 94448 --- [nio-8080-exec-4] o.h.engine.jdbc.spi.SqlExceptionHelper
     : SQL Error: 23503, SQLState: 23503
2020-09-11 16:45:12.449 ERROR 94448 --- [nio-8080-exec-4] o.h.engine.jdbc.spi.SqlExceptionHelper
     : Referential integrity constraint violation: "FKAWPXQE7N22N3E3IKCWSEHQMDX: PUBLIC.EMPLOYEE_AVAILABILITY 
     FOREIGN KEY(EMPLOYEE_ID) REFERENCES PUBLIC.EMPLOYEE(ID) (19)"; SQL statement:
     delete from employee where id=? and version=? [23503-173]
2020-09-11 16:45:12.449  INFO 94448 --- [nio-8080-exec-4] o.h.e.j.b.internal.AbstractBatchImpl
     : HHH000010: On release of batch it still contained JDBC statements
2020-09-11 16:45:12.449 ERROR 94448 --- [nio-8080-exec-4] o.h.i.ExceptionMapperStandardImpl
     : HHH000346: Error during managed flush [org.hibernate.exception.ConstraintViolationException: 
     could not execute statement]
```

I tried going into the REST API to try to delete a tenant by his/her ID, but I could not locate where different tenants' IDs were. I also tried deleting the `node_modules` directory within the frontend directory and rebuilding bc it contained a `migrations` directory, but that did not solve the issue.

Additionally, I tried running the scheduler using the 'schedule' button and I got no response from the UI nor the console. 

Any help with regard to both issues would be greatly appreciated. Thank you!

**Comment by Christopher-Chianelli** [comment]
What the notification is saying is this: the Employee you are trying to delete is still referenced by Shifts. In order to remove an Employee, it cannot be referenced anywhere. What that means is you need to find all the shifts and timebuckets that have the Employee as its assigned employee or rotation employee and change it either to unassigned or another employee. Define "No response" - you should of at least got a notification that it was scheduling the schedule. Depending on how large the dataset is, it can take a minute to find an initial solution.

The alternative to this error message would be to "archive" the Employee (which means it will be kept in the database, but no longer used in planning.

**Comment by dlymarg** [comment]
Do I have to remove employees scheduled within the current week to remove an employee from the database? I could not find the option to archive an employee. I also tried removing the other tenants in the UI except for Hospital Los Angeles to see if I could remove an employee after that (considering employees in the hospital are also in other workplaces' rosters), but I ran into the same error message.

It appears that in my version of Optaweb, none of the buttons on the top right of the schedule tab (schedule, create shift, export to Excel, etc.) appear to be responsive. I do not get any sort of notification in the console I am running the planner from nor in the UI

**Comment by Christopher-Chianelli** [comment]
As of right now, yes (as well as past weeks, shift templates, etc.). We don't current support "archiving" employees, although we are considering adding it. The employees are not shared between tenants; they use the same random name generator. A potential fix would be to cascade delete, but that will delete any shifts/time buckets the employee had assigned to them.

What browser are you using, and on what device?

**Comment by dlymarg** [comment]
I am using Safari on a MacBook Pro running macOS 10.15.6.

Is there a way to delete multiple shifts based on an employee's name or is the only option to remove each shift for a single employee one-by-one?

**Comment by Christopher-Chianelli** [comment]
Currently, only one by one. If you could connect to the database, you could create a query that sets the employee of shifts and shift templates/rotation to null (which would then allow you to delete the employee)

**Comment by dlymarg** [comment]
I found the solution to the unresponsive 'schedule' button: instead of using Safari to open localhost, I used Firefox instead.

I am still experimenting with the remove employee function

**Comment by Christopher-Chianelli** [comment]
Fixed the unresponsive schedule button in https://github.com/kiegroup/optaweb-employee-rostering/pull/500 ; Safari doesn't have `innerText` like Firefox and Chrome (despite it being on https://caniuse.com/innertext )
