### ISSUE TITLE
Customized constraint stream provider

### ISSUE THREAD

**Issue by pixnbit** [kiegroup/optaweb-employee-rostering#502]
I just post the question on Stackoverflow, might as well send one here (I'll post back any answer here back to SO)

https://stackoverflow.com/questions/64127755/how-to-customize-constraintprovider-in-optaplanner

> This is a shift scheduling application. I'm already dynamically control some of the constraints on/off by changing weight, which is great. And some specific constraints can already be dynamically controlled with the planning object properties (Employee's contract maximum). I still haven't found a way to make the ConstraintProvider parametrized based on configuration. My question is:
> Can a ConstraintProvider be programmatically created, instead of defining in the solverConfig.xml? So I can inject my own parameters
> I would want this constraint to be dyniamically adjusted with not just 10 hours fixed duration (that 10 * 60 hardcoded value):

```
Constraint breakBetweenNonConsecutiveShiftsIsAtLeastTenHours(ConstraintFactory constraintFactory) {
        return getAssignedShiftConstraintStream(constraintFactory)
                .join(Shift.class,
                      equal(Shift::getEmployee),
                      lessThan(Shift::getEndDateTime, Shift::getStartDateTime))
                .filter((s1, s2) -> !Objects.equals(s1, s2))
                .filter((s1, s2) -> s1.getEndDateTime().until(s2.getStartDateTime(), ChronoUnit.HOURS) < 10)
                .penalizeConfigurableLong(CONSTRAINT_BREAK_BETWEEN_NON_CONSECUTIVE_SHIFTS, (s1, s2) -> {
                    long breakLength = s1.getEndDateTime().until(s2.getStartDateTime(), ChronoUnit.MINUTES);
                    return (10 * 60) - breakLength;
                });
    }

```

What's the best approach to customize the constraints? They're created with the solverConfig.xml.

**Comment by Christopher-Chianelli** [comment]
Currently, the best way is to create a custom class to store the duration (ex: MinimumBreakBetweenNonConsecutiveShifts) add it as a field to Roster, and annotate the field with `@ProblemFact`. Then you can join the stream with the problem fact with `constraintFactory.from(...).join(MinimumBreakBetweenNonConsecutiveShifts.class)` We are currently discussing alternative methods for access to problem facts here: https://kie.zulipchat.com/#narrow/stream/232679-optaplanner/topic/Constraint.20context

**Comment by pixnbit** [comment]
Thanks! ProblemFact is better than my hacky solution (Shift.getMinimumBreakBetweenNonConsecutiveShifts()), and I think a Constraint Context would make more sense.
