### ISSUE TITLE
How to get the current value of AppState? What code need to call?

### ISSUE THREAD

**Issue by JiangWeian** [kiegroup/optaweb-employee-rostering#514]

**Comment by Christopher-Chianelli** [comment]
AppState is stored in the `redux` store. How to get `AppState` differs from where you are calling it:

- For selectors (functions that get something from App State), `AppState` is passed in as a parameter: https://github.com/kiegroup/optaweb-employee-rostering/blob/ab48823f63fc743e2ce142a9dcdc6b068a4a213a/optaweb-employee-rostering-frontend/src/store/skill/selectors.ts#L19-L24)
- For operations (functions that modify App State), `AppState` is accessed via the `state` parameter: https://github.com/kiegroup/optaweb-employee-rostering/blob/ab48823f63fc743e2ce142a9dcdc6b068a4a213a/optaweb-employee-rostering-frontend/src/store/skill/operations.ts#L60-L61
- For components/UI, use useSelector: https://github.com/kiegroup/optaweb-employee-rostering/blob/ab48823f63fc743e2ce142a9dcdc6b068a4a213a/optaweb-employee-rostering-frontend/src/ui/pages/rotation/RotationPage.tsx#L44-L48
- For class based components, use `connect` with a `mapStateToProps`: https://github.com/kiegroup/optaweb-employee-rostering/blob/ab48823f63fc743e2ce142a9dcdc6b068a4a213a/optaweb-employee-rostering-frontend/src/ui/pages/employee/EmployeesPage.tsx#L53-L73 https://github.com/kiegroup/optaweb-employee-rostering/blob/ab48823f63fc743e2ce142a9dcdc6b068a4a213a/optaweb-employee-rostering-frontend/src/ui/pages/employee/EmployeesPage.tsx#L283
