### ISSUE TITLE
Why is excel table exported in the shift and adjust page when the employee name and time are not in the same row?

### ISSUE THREAD

**Issue by JiangWeian** [kiegroup/optaweb-employee-rostering#544]
As shown in the figure:
![TIM图片20201209111837](https://user-images.githubusercontent.com/56569509/101570015-82022b00-3a10-11eb-94e2-a1bc7b6ebf0b.png)

**Comment by Christopher-Chianelli** [comment]
To improve human readability when there are multiple shifts involved. If you have 3 shifts from `2020-12-07 06:00 -- 2020-12-07 14:00`, in a particular spot, it will look like this:

```
Start                            End                                         Employee
2020-12-07 06:00                 |2020-12-07 14:00                          |
                                                                            |Amy Cole
                                                                            |Flo Li
                                                                            |Beth Green
2020-12-07 09:00                 |2020-12-07 17:00
                                                                            |Bill Cole
                                                                            |Charlie Li
```
The excel file is designed to be consumed by humans; machines can read the shift data from JSON using the REST API.

There are several other ways it could be designed:

- Include Start and End for each individual shift - this make it hard to see Shift Groups
- Put Employees in multiple columns (from C to `C + max(employees in same shift group))`; 
 can take too much horizontal space

You can modify how the excel file looks like here: https://github.com/kiegroup/optaweb-employee-rostering/blob/master/optaweb-employee-rostering-backend/src/main/java/org/optaweb/employeerostering/util/ShiftRosterXlsxFileIO.java
