### ISSUE TITLE
Why is it that the firstDraftDate is less than one day and the lastHistoricalDate is two days less?

### ISSUE THREAD

**Issue by JiangWeian** [kiegroup/optaweb-employee-rostering#545]
I chose firstDraftDate is November 30, 2020 at the front end:
![TIM图片20201211161708](https://user-images.githubusercontent.com/56569509/101879478-5b88ef00-3bcc-11eb-8082-e5b42fec3882.png)

But in the back end, it's become 2020.11.29:
![TIM图片20201211161511](https://user-images.githubusercontent.com/56569509/101879602-8f641480-3bcc-11eb-803f-c37a58457723.png)

**Comment by Christopher-Chianelli** [comment]
Most likely time zone conversion (that is done in frontend by moment and converts the date into the UTC date, which can change the local date part)
