### ISSUE TITLE
How to make the employees who have been on the night shift not go to work the next morning?

### ISSUE THREAD

**Issue by JiangWeian** [kiegroup/optaweb-employee-rostering#559]
rule "No more than 2 consecutive shifts"
    when
        $s : Shift(
                employee != null,
                $e : employee,
                $firstEndDateTime : endDateTime)
        $s2: Shift(
                employee == $e,
                $firstEndDateTime == startDateTime,
                this != $s,
                $secondEndDateTime : endDateTime)
        $s3: Shift(
                employee == $e,
                $secondEndDateTime == startDateTime,
                this != $s,
                this != $s2)
    then
        scoreHolder.penalize(kcontext, $s3.getLengthInMinutes());
end

This rule does not prevent workers who have worked late from working early the next day.How to modify this rule.

**Comment by rgeos** [comment]
That is indeed a real world situation.

[This may help](https://github.com/kiegroup/optaweb-employee-rostering/issues/491#issuecomment-680807886).
