### ISSUE TITLE
Did the Spot Roster Tab disappear?

### ISSUE THREAD

**Issue by hertaberlin** [kiegroup/optaweb-employee-rostering#585]

**Comment by yurloc** [comment]
No, I don't think so. What version of employee rostering are you using?

**Comment by hertaberlin** [comment]
I'm talking about this tab on which u can see all the spots in one place, as opposed to selecting one spot at time as it is the case in the latest commit.

![image](https://user-images.githubusercontent.com/49375703/109964716-f08c1780-7ce5-11eb-980d-77684d1b098e.png)

**Comment by yurloc** [comment]
Ah, OK. The screenshot is from an old video about a very early stage of the Employee Rostering project. Yes, the Spot roster page is gone. The complete schedule is now available on the Scheduling page:
![Screen Shot 2021-03-04 at 14 08 14](https://user-images.githubusercontent.com/673386/109969346-13bdc380-7cf4-11eb-9f5d-1505da5e0cba.png)
Use the spot dropdown to browse through different spots and view their schedules.
