### ISSUE TITLE
DB errors when first booting - can't add records (contract etc) either.

### ISSUE THREAD

**Issue by midijohnny** [kiegroup/optaweb-employee-rostering#589]
I seem to get a H2 DB error when booting up - I can't add any records.

I see this in the logs: do I need more memory on my machine? (Or can I reconfigure to an on-disk DB instead?)

```
2021-03-14 19:20:21.781  INFO 14008 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 69 ms
2021-03-14 19:20:26.562  WARN 14008 --- [nio-8080-exec-9] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 50200, SQLState: HYT00
2021-03-14 19:20:26.563 ERROR 14008 --- [nio-8080-exec-9] o.h.engine.jdbc.spi.SqlExceptionHelper   : Timeout trying to lock table "TENANT"; SQL statement:
select tenant0_.id as id1_13_, tenant0_.name as name2_13_, tenant0_.version as version3_13_ from tenant tenant0_ order by tenant0_.id [50200-173]
```

**Comment by midijohnny** [comment]
I navigated to the URL
```
http://localhost:8080/h2-console
```

And the test-connection works ok?
Anybody else seen this issue?

**Comment by Christopher-Chianelli** [comment]
I haven't encountered this error locally before, but it look like the query timeout when attempting to get a lock ( https://www.logicbig.com/tutorials/java-ee-tutorial/jpa/pessimistic-lock-exception.html ). This probably occurred when the example datasets was being generated. You can try disabling example dataset creation by passing `-Doptaweb.generator.initial.data=EMPTY` when starting the application (https://github.com/kiegroup/optaweb-employee-rostering/blob/master/optaweb-employee-rostering-docs/src/main/asciidoc/Introduction/SystemProperties/SystemProperties-section.adoc). You would need to create a Tenant in the Admin page before adding Skills, Spots, Contracts, Employees, Time Buckets and Shifts.

**Comment by midijohnny** [comment]
Thanks for getting back on this Christopher-Chianelli!
