### ISSUE TITLE
Assisted manual editing/scheduling 

### ISSUE THREAD

**Issue by pixnbit** [kiegroup/optaweb-employee-rostering#601]
We've been using the fully automated scheduling with the rules we defined. It's been working great. However often times a store manager would like to manually change individual shifts. Is there a way to provide a list of choices ranked by the store? I know this would result in a local optimal solution, but it's also a valid case where managers want manual editing, with some Optaplanner help.

One way I see it can be done is having the entire Roster with just this single shift and provide all the unassigned employees for optimization. But this would only produce one solution. 

Another solution is to try to assign every employee to this shift, and evaluate the score each time, and rank the score to get a list of recommendations. I'm basically manually doing a one-step optimization.  

Is there a better way of doing this? Would optimization provide a list of scores for the options considered? Thanks!

**Comment by Christopher-Chianelli** [comment]
Sounds like you want pinning. You can already pin shifts in OptaWeb Employee Rostering -- click the shift, click the edit button, then check the "is pinned" checkbox. This tells OptaPlanner not to change the assigned employee for that particular shift (and you can change the assigned employee via the employee field).

In regards to "get recommendations for a shift leaving the rest of the roster the same", you can `@Inject` the `ScoreManager` to calculate the score of a particular solution (which would allow you to loop through all possible assignments of the Shift and see different options). Note that the "best" assignment for a particular shift depends on all the other shift in the roster, so by changing a single shift you impact the "best" assignments for other shifts.

**Comment by pixnbit** [comment]
Thanks for the answer. Pinned option makes sense, but how do I get a list of ranked candidates by scores?
