### ISSUE TITLE
Create Availability - Date Range

### ISSUE THREAD

**Issue by gcareri** [kiegroup/optaweb-employee-rostering#614]
Hello everyone, 

I receive an error when I try to set a range of unavailable date (from May 07, 12:00 AM to May 09, 12:00 AM).

Is there a limit in the date range?

I attached the error.

Thanks in advance!
Giuseppe

![create-availability](https://user-images.githubusercontent.com/12231672/117271553-9715a580-ae5a-11eb-9e1f-fb21348c4465.png)
![stack-error](https://user-images.githubusercontent.com/12231672/117271554-97ae3c00-ae5a-11eb-8b65-5b6113f8ab16.png)

**Comment by Christopher-Chianelli** [comment]
Yes there is a limit of 1 day (or more exactly, 28 hours to support DST changes) . You can find and modify it here: https://github.com/kiegroup/optaweb-employee-rostering/blob/27290a9f183395bfca54afc6827fe0009f4b7112/optaweb-employee-rostering-backend/src/main/java/org/optaweb/employeerostering/domain/employee/EmployeeAvailability.java#L75-L79

**Comment by gcareri** [comment]
Thanks!
