### ISSUE TITLE
Shifts created by Publish button isn't following Rotation Schedule

### ISSUE THREAD

**Issue by otherwish** [kiegroup/optaweb-employee-rostering#657]
Using 8.8.0 code via Docker. The shifts I am creating via rotation are Monday through Friday. When I publish a schedule, the following week is being filled in Tuesday through Saturday. Is this an expected behavior?

**Comment by Christopher-Chianelli** [comment]
Depends on Timezone and configured schedule start date. For example, if the Schedule Start Day is a Tuesday, then Rotation Day 0 (the first column) = a Tuesday.

**Comment by otherwish** [comment]
Looking at the database data, the firstdraftdate was set to a Monday. Edited the value to a Sunday seemed to fix it. Thank you!
