### ISSUE TITLE
local openshift

### ISSUE THREAD

**Issue by jsc29** [kiegroup/optaweb-employee-rostering#67]
Hi,

I am starting to llok at this project, first time I am using openshift. I got it deployed correctly on a local openshift. but now I can only get the widlfly welcome page
http://optashift-employee-rostering-myproject.xxx.xxx.xx.xxx.nip.io/

how can I access the webapp ?

thanks

**Comment by artemious7** [comment]
I'm also having trouble deploying to an openshift server. But [I can't deploy it locally either](https://github.com/kiegroup/optashift-employee-rostering/issues/62). Can you, please, share your steps? What did you use to make it work locally?

**Comment by ge0ffrey** [comment]
@jsc29 Did you follow the steps in the readme? (They might be new since you tried it)

https://github.com/kiegroup/optashift-employee-rostering/blob/master/README.adoc#locally-with-openshift-origin

**Comment by EsajeeSolutions** [comment]
tried all ways, but could not make it by running locally, some error which i am not able to trace

**Comment by ge0ffrey** [comment]
Can you copy paste the error?

**Comment by EsajeeSolutions** [comment]
i can not get details and might be i don't know how to trace it further,
but oc status, show bulild error, i have increased memory from 1 to 2 and
even 4 GB with 4 cpu, but same results, was reluctant to buy 50$ package,
will it run on that smoothly ?





Regards

-- 
Siddique Ahmad

**Comment by EsajeeSolutions** [comment]
accidently i run standalone server and deploy app there and it is working fine,
