### ISSUE TITLE
[bug] first shift not editable due to data-popper-reference-hidden

### ISSUE THREAD

**Issue by xunxky** [kiegroup/optaweb-employee-rostering#691]
i will go to bed now so i keep it short. 
for some reason klicking on the first shift the data popover is assigned with data-popper-reference-hidden=true for the later ones this is false in my test. 

if i decide to use this tool i will be back with more detailed report and maybe a fix too.

**Comment by Christopher-Chianelli** [comment]
Thank you for pointing out the cause of that annoying bug. Look like Patternfly CSS was disabling pointer-events because of that attribute. I'll have a PR open shortly.

**Comment by xunxky** [comment]
yea the other bug that is causing this otherwise mostly correct behavior is the unnecessary div in the event wrapper
