### ISSUE TITLE
Delete object request is not working

### ISSUE THREAD

**Issue by lacroixca** [kiegroup/optaweb-employee-rostering#73]
Every time I try to delete a worker, skill, shift, etc. I get an error (see photo). Why is this?

![optashift02](https://user-images.githubusercontent.com/1235235/36943771-e3a8a572-1f5c-11e8-873d-e8ae083dcb49.jpg)

**Comment by ge0ffrey** [comment]
Probably becuase it's used somewhere and there's a foreign key violation. The UI needs to display this better.

**Comment by FaisalDefry** [comment]
hello, is this confirmed as a bug?

**Comment by Christopher-Chianelli** [comment]
Closing since the UI now informs the user of the foreign key violation and explains how to fix it
