### ISSUE TITLE
Problem with runLocally.sh

### ISSUE THREAD

**Issue by Luko92** [kiegroup/optaweb-employee-rostering#731]
Hi,

After building the project I've tryed to run it with the following command (I'm on w10):

`CD C:\Users\Luca\Desktop\Shift\optaweb-employee-rostering-main\optaweb-employee-rostering-main
bash `

The output is: runLocally.sh: line 62: java: command not foun

I'm including the script.

Thanks for your support!
[runLocally.zip](https://github.com/kiegroup/optaweb-employee-rostering/files/7650586/runLocally.zip)
d

**Comment by Christopher-Chianelli** [comment]
You will need to download Java 11 or above. You can obtain the required binaries at https://adoptium.net/ (and its installation guide: https://adoptium.net/installation.html )
