### ISSUE TITLE
Make datasource connection and database type configurable through environment properties for openshift

### ISSUE THREAD

**Issue by ge0ffrey** [kiegroup/optaweb-employee-rostering#8]
OpenShift doesn't like it that we hardcode our datasource username, password, hibernate dialect type etc.

- Make it configurable through environment variables, as per openshift guidelines
- Document that in our readme (at the bottom, as optional)
- Prove that it works on postgresql and 1 other database (mysql? mariasql?)
- Adjust the openshift template to setup postgresql or mysql and set those env variables.
- Prove that it still works out-of-the-box locally without any environment variables against WildFly's H2 example datasource. We don't want to have to install a database to test it locally.

Looks like the datasource is really just a wildfly problem which is already solved, so it's just a matter of copy-pasting the wildflyOnOpenShift docs (or linking it) in our readme and making the datasource name configurable. So it's really just the dialect and the datasource name that need to be configurable:
https://github.com/ge0ffrey/optashift-employee-rostering/blob/master/optashift-employee-rostering-shared/src/main/resources/META-INF/persistence.xml#L6
https://github.com/ge0ffrey/optashift-employee-rostering/blob/master/optashift-employee-rostering-shared/src/main/resources/META-INF/persistence.xml#L13

It would be really cool if hibernate's `persistence.xml` supports something like `logback.xml` does, to allow a property to be overridden by an env variable, but meanwhile also give it a default if it isn't:

```
<!-- To override the debug log level from the command line, use the VM option "-Dlogback.level.org.optaplanner=trace" -->
<logger name="org.optaplanner" level="${logback.level.org.optaplanner:-debug}"/>
```

**Comment by ge0ffrey** [comment]
@DuncanDoyle You interested in handling this one?

**Comment by DuncanDoyle** [comment]
@ge0ffrey Yes, I can take this one.

**Comment by Christopher-Chianelli** [comment]
Once #191 and #188 are merged, this issue should be marked resolved.
