### ISSUE TITLE
Problem with JBoss Nexus

### ISSUE THREAD

**Issue by albertobenincasa** [kiegroup/optaweb-employee-rostering#819]
Good morning. Since a few days, If I try to compile different versions of optaweb-rostering, I get the following error:

`
[INFO] Scanning for projects...
Downloading from jboss-public-repository-group: https://repository.jboss.org/nexus/content/groups/public/org/optaplanner/optaplanner-build-parent/8.22.0-SNAPSHOT/maven-metadata.xml
Downloaded from jboss-public-repository-group: https://repository.jboss.org/nexus/content/groups/public/org/optaplanner/optaplanner-build-parent/8.22.0-SNAPSHOT/maven-metadata.xml (620 B at 1.1 kB/s)
Downloading from jboss-public-repository-group: https://repository.jboss.org/nexus/content/groups/public/org/optaplanner/optaplanner-build-parent/8.22.0-SNAPSHOT/optaplanner-build-parent-8.22.0-20220523.113833-90.pom
[ERROR]
[ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for org.optaweb.employeerostering:optaweb-employee-rostering:8.22.0-SNAPSHOT: Could not transfer artifact org.optaplanner:optaplanner-build-parent:pom:8.22.0-20220523.113833-90 from/to jboss-public-repository-group (https://repository.jboss.org/nexus/content/groups/public/): transfer failed for https://repository.jboss.org/nexus/content/groups/public/org/optaplanner/optaplanner-build-parent/8.22.0-SNAPSHOT/optaplanner-build-parent-8.22.0-20220523.113833-90.pom, status: 503 Service Unavailable and 'parent.relativePath' points at no local POM @ org.optaweb.employeerostering:optaweb-employee-rostering:8.22.0-SNAPSHOT, /home/bys/Documenti/workspace/wfm-optaweb/pom.xml, line 6, column 11
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.optaweb.employeerostering:optaweb-employee-rostering-backend:8.22.0-SNAPSHOT (/home/bys/Documenti/workspace/wfm-optaweb/optaweb-employee-rostering-backend/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.optaweb.employeerostering:optaweb-employee-rostering:8.22.0-SNAPSHOT: Could not transfer artifact org.optaplanner:optaplanner-build-parent:pom:8.22.0-20220523.113833-90 from/to jboss-public-repository-group (https://repository.jboss.org/nexus/content/groups/public/): transfer failed for https://repository.jboss.org/nexus/content/groups/public/org/optaplanner/optaplanner-build-parent/8.22.0-SNAPSHOT/optaplanner-build-parent-8.22.0-20220523.113833-90.pom, status: 503 Service Unavailable and 'parent.relativePath' points at no local POM @ org.optaweb.employeerostering:optaweb-employee-rostering:8.22.0-SNAPSHOT, /home/bys/Documenti/workspace/wfm-optaweb/pom.xml, line 6, column 11 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
`

Seems to be a jboss problem. Does it happens to someone else too?

Thanks

**Comment by yurloc** [comment]
> Does it happens to someone else too?

Not at this moment on my machine. 503 seems like a temporary problem with the Nexus server.

 How often does it happen to you?  Did it happen once? Does it happen regularly or is it even permanent?

**Comment by triceo** [comment]
Unfortunately, `https://repository.jboss.org/` has been very unstable lately.
They're working on it, but the downtime has been fairly frequent and intermittent.
Sorry for that.

**Comment by albertobenincasa** [comment]
Honestly, this has never happened to me before, this is the first time and it has been going on for a few day now.

I think I have to wait then :D .

Thanks for the answers.

**Comment by firzanarmani** [comment]
I'm experiencing this issue too. Is there a fix or a workaround (that maybe doesn't use JBoss Nexus)?

**Comment by albertobenincasa** [comment]
The problem still persists today. Do you know any workaround maybe?

**Comment by triceo** [comment]
The workaround is to locally build the entire path towards this repo, from source - so at the very least Drools and OptaPlanner. To be clear - we definitely do not expect users to have to do that. This downtime is just ridiculous, and embarassing.

**Comment by albertobenincasa** [comment]
> The workaround is to locally build the entire path towards this repo, from source - so at the very least Drools and OptaPlanner. To be clear - we definitely do not expect users to have to do that. This downtime is just ridiculous, and embarassing.

Could you explain in more detail how to implement this procedure? Thank you so much

**Comment by yurloc** [comment]
@albertobenincasa 

In a clean working directory:

1. Clone the bootstrap repo:
    ```sh
    git clone git@github.com:kiegroup/droolsjbpm-build-bootstrap.git
    ```
2. Clone all the repositories required to build `optaweb-employee-rostering`:
    ```sh
    ./droolsjbpm-build-bootstrap/script/git-clone-others.sh --repo-list=droolsjbpm-build-bootstrap,kie-soup,droolsjbpm-knowledge,drools,optaplanner,optaweb-employee-rostering
    ```
3. Build them all:
    ```sh
    ./droolsjbpm-build-bootstrap/script/mvn-all.sh clean install -nsu -DskipTests
    ```

If you don't want to start from scratch, skip steps 1 and 2 and instead of that, manually clone repositories that you're missing and then run:
```sh
./droolsjbpm-build-bootstrap/script/mvn-all.sh clean install -nsu -DskipTests
```

or if you have some other kiegroup repositories in the working directory that you don't want to build than you can skip them by passing an explicit repository list:
```sh
./droolsjbpm-build-bootstrap/script/mvn-all.sh --repo-list=droolsjbpm-build-bootstrap,kie-soup,droolsjbpm-knowledge,drools,optaplanner,optaweb-employee-rostering clean install -nsu -DskipTests
```
